# Generated by Django 5.2.5 on 2025-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('ativo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='imagens-pessoas/')),
                ('telefone', models.CharField(max_length=21, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Trabalhadores',
            },
        ),
    ]
