# Generated by Django 5.2.5 on 2025-08-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('ativo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='imagens-pessoas/')),
                ('telefone', models.CharField(max_length=21, unique=True)),
                ('endereco', models.CharField(verbose_name='Endereço')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
