# Generated by Django 5.2.5 on 2025-08-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('data_agendado', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('E', 'Executando'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente', verbose_name='Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.servico', verbose_name='Serviço contratado')),
                ('trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.trabalhador', verbose_name='Trabalhador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
