# Generated by Django 5.2.5 on 2025-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do serviço')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
