# Generated by Django 5.2.5 on 2025-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('tipo_servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='TipoServico',
        ),
    ]
