"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fyqh3m%#kwk2drh614o!rgxs_g4o7vz-rgznry@w(lt8lbnusm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #modules
    'core',
    'cadastros',
    'servicos',
    'relatorios',

    #submodules
    'core.bases',
    'core.pessoas',

    'cadastros.clientes',
    'cadastros.trabalhadores',
    'cadastros.empresas',
    
    'servicos.tipo_servicos',
    'servicos.agendamentos'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            #base
            BASE_DIR / 'templates',

            #Módulos
            BASE_DIR / 'cadastros' / 'templates',
            BASE_DIR / 'servicos' / 'templates',
            BASE_DIR / 'relatorios' / 'templates',


            #submodulos
            BASE_DIR / 'core' / 'bases' / 'templates',
            BASE_DIR / 'core' / 'pessoas' / 'templates',
            BASE_DIR / 'core' / 'auth' / 'templates',

            BASE_DIR / 'cadastros' / 'clientes' / 'templates',
            BASE_DIR / 'cadastros' / 'empresas' / 'templates',
            BASE_DIR / 'cadastros' / 'trabalhadores' / 'templates',

            BASE_DIR / 'servicos' / 'agendamentos' / 'templates',
            BASE_DIR / 'cadastros' / 'tipo_servicos' / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.parent / 'database.sqlite3',
    }
}

# WhiteNoise specific configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "LOCATION": BASE_DIR / "media"
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# LOGGING = {
#     'version': 1,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'DEBUG',
#     },
# }

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

#All dirs that include static files are required to be here.
STATICFILES_DIRS = [
    BASE_DIR / 'static',

    #Módulos
    BASE_DIR / 'relatorios' / 'static',


    #submodulos
    BASE_DIR / 'core' / 'bases' / 'static',
    BASE_DIR / 'core' / 'pessoas' / 'static',
    BASE_DIR / 'core' / 'auth' / 'static',

    BASE_DIR / 'cadastros' / 'clientes' / 'static',
    BASE_DIR / 'cadastros' / 'empresas' / 'static',
    BASE_DIR / 'cadastros' / 'trabalhadores' / 'static',
    
    BASE_DIR / 'servicos' / 'agendamentos' / 'static',
    BASE_DIR / 'servicos' / 'tipo_servicos' / 'static'
]

# Path for static files to be saved when 'manage.py collectstatic' for production
STATIC_ROOT = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'


LOGIN_URL = "/core/auth/login/"
LOGIN_REDIRECT_URL = '/home/'