# Generated by Django 5.2.5 on 2025-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('cnpj', models.CharField(default=None, max_length=14, unique=True, verbose_name='CNPJ')),
                ('nome_fantasia', models.CharField(default=None, max_length=255, verbose_name='Nome-fantasia')),
                ('razao_social', models.CharField(default=None, max_length=255, verbose_name='Razão Social')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
