# Generated by Django 5.2.5 on 2025-08-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('ativo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='imagens-pessoas/')),
                ('telefone', models.CharField(max_length=21, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do serviço')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('ativo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='imagens-pessoas/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('data_agendado', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('E', 'Executando'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.cliente', verbose_name='Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.servico', verbose_name='Serviço contratado')),
                ('trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.trabalhador', verbose_name='Trabalhador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
