# Generated by Django 5.2.5 on 2025-08-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='trabalhador',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.DeleteModel(
            name='Trabalhador',
        ),
    ]
