#Agendamento.status
AGENDAMENTO_STATUS_PENDENTE = 'P'
AGENDAMENTO_STATUS_EXECUTANDO =  'E'
AGENDAMENTO_STATUS_FINALIZADO = 'F'
AGENDAMENTO_STATUS_CANCELADO = 'C'

C_TIPO_STATUS_AGENDAMENTO = (
    (AGENDAMENTO_STATUS_PENDENTE, "Pendente"),
    (AGENDAMENTO_STATUS_EXECUTANDO, "Executando"),
    (AGENDAMENTO_STATUS_FINALIZADO, "Finalizado"),
    (AGENDAMENTO_STATUS_CANCELADO, "Cancelado"),
)